### ISSUE TITLE
construncción de la ventana1 primera parte  

### ISSUE THREAD

**Issue by DanielHenaoC** [DanielHenaoC/Clase9#1]
Construir la ventana1 y hacer el formulario para ingresar la información del cliente

**Comment by Emanuelv2005** [comment]
Saludos. voy a encargarme de esta funcionalidad

**Comment by DanielHenaoC** [comment]
Listo trabajo cumplido, por favor revisar el nuevo issue para hacer en ventana1.py el formulario de registro del usuario

**Comment by DanielHenaoC** [comment]
Gracias

**Comment by DanielHenaoC** [comment]
Queda pendiente.
